[versions]
gson = "2.11.0"
tiny-remapper = "0.10.4"

[libraries]
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
fabric-tiny-remapper = { module = "net.fabricmc:tiny-remapper", version.ref = "tiny-remapper" }
